// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $catalog_add_modal from "./routes/catalog/add-modal.tsx";
import * as $catalog_buttons from "./routes/catalog/buttons.tsx";
import * as $catalog_edit_dialog from "./routes/catalog/edit-dialog.tsx";
import * as $catalog_index from "./routes/catalog/index.tsx";
import * as $catalog_schedule_item from "./routes/catalog/schedule-item.tsx";
import * as $catalog_time_display from "./routes/catalog/time-display.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $AddModalCatalog from "./islands/AddModalCatalog.tsx";
import * as $AddScheduleModal from "./islands/AddScheduleModal.tsx";
import * as $App from "./islands/App.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $EditDialogCatalog from "./islands/EditDialogCatalog.tsx";
import * as $LoginScreen from "./islands/LoginScreen.tsx";
import * as $QuickEditDialog from "./islands/QuickEditDialog.tsx";
import * as $ScheduleItemCatalog from "./islands/ScheduleItemCatalog.tsx";
import * as $TimelineScreen from "./islands/TimelineScreen.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/catalog/add-modal.tsx": $catalog_add_modal,
    "./routes/catalog/buttons.tsx": $catalog_buttons,
    "./routes/catalog/edit-dialog.tsx": $catalog_edit_dialog,
    "./routes/catalog/index.tsx": $catalog_index,
    "./routes/catalog/schedule-item.tsx": $catalog_schedule_item,
    "./routes/catalog/time-display.tsx": $catalog_time_display,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AddModalCatalog.tsx": $AddModalCatalog,
    "./islands/AddScheduleModal.tsx": $AddScheduleModal,
    "./islands/App.tsx": $App,
    "./islands/Counter.tsx": $Counter,
    "./islands/EditDialogCatalog.tsx": $EditDialogCatalog,
    "./islands/LoginScreen.tsx": $LoginScreen,
    "./islands/QuickEditDialog.tsx": $QuickEditDialog,
    "./islands/ScheduleItemCatalog.tsx": $ScheduleItemCatalog,
    "./islands/TimelineScreen.tsx": $TimelineScreen,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
