// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $AddScheduleModal from "./islands/AddScheduleModal.tsx";
import * as $App from "./islands/App.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $LoginScreen from "./islands/LoginScreen.tsx";
import * as $QuickEditDialog from "./islands/QuickEditDialog.tsx";
import * as $TimelineScreen from "./islands/TimelineScreen.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AddScheduleModal.tsx": $AddScheduleModal,
    "./islands/App.tsx": $App,
    "./islands/Counter.tsx": $Counter,
    "./islands/LoginScreen.tsx": $LoginScreen,
    "./islands/QuickEditDialog.tsx": $QuickEditDialog,
    "./islands/TimelineScreen.tsx": $TimelineScreen,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
